### ISSUE TITLE
Add option to distinguish between text and audio

### ISSUE THREAD

**Issue by Undead34** [renatopda8/LanguageChanger#1]
Hello, I know that Riot already has the option from the client but I would like to know if we could add the option to have the voices in Japanese, for example, and the text in English.

**Comment by renatopda8** [comment]
Hey, just ran a quick search about the topic.

Didn't find any tools that already do that, changing just the audio without changing the text.
It's not something that Riot supports, as they did with the config file used by this app to change the language.

It'd probably be closer to modding the game. You'd need to change whatever file keeps the audio, and somehow prevent the client from updating them and replacing on next startup.

Anyway, it's certainly out of the scope of this project, as it simply changes one line on a config file.

Thank you for asking
